export const data = [
  {
    songName: "Electric Feel",
    artist: "MGMT",
    dateStreamed: "2024-02-01",
    streamCount: 10,
    userID: "004",
  },
  {
    songName: "Can't Stop",
    artist: "Red Hot Chili Peppers",
    dateStreamed: "2024-02-02",
    streamCount: 14,
    userID: "015",
  },
  {
    songName: "Sunflower",
    artist: "Post Malone",
    dateStreamed: "2024-02-03",
    streamCount: 11,
    userID: "106",
  },
  {
    songName: "Lose Yourself",
    artist: "Eminem",
    dateStreamed: "2024-04-04",
    streamCount: 12,
    userID: "017",
  },
  {
    songName: "Bohemian Rhapsody",
    artist: "Queen",
    dateStreamed: "2024-04-05",
    streamCount: 15,
    userID: "101",
  },
  {
    songName: "Radioactive",
    artist: "Imagine Dragons",
    dateStreamed: "2024-04-06",
    streamCount: 8,
    userID: "012",
  },
  {
    songName: "Don't Start Now",
    artist: "Dua Lipa",
    dateStreamed: "2024-04-07",
    streamCount: 9,
    userID: "003",
  },
  {
    songName: "Somebody That I Used to Know",
    artist: "Gotye",
    dateStreamed: "2024-04-08",
    streamCount: 11,
    userID: "004",
  },
  {
    songName: "Billie Jean",
    artist: "Michael Jackson",
    dateStreamed: "2024-04-09",
    streamCount: 14,
    userID: "005",
  },
  {
    songName: "Shallow",
    artist: "Lady Gaga",
    dateStreamed: "2024-05-10",
    streamCount: 13,
    userID: "006",
  },
  {
    songName: "Starboy",
    artist: "The Weeknd",
    dateStreamed: "2024-05-11",
    streamCount: 12,
    userID: "007",
  },
  {
    songName: "Happier Than Ever",
    artist: "Billie Eilish",
    dateStreamed: "2024-05-12",
    streamCount: 9,
    userID: "001",
  },
  {
    songName: "bad guy",
    artist: "Billie Eilish",
    dateStreamed: "2024-05-13",
    streamCount: 7,
    userID: "102",
  },
  {
    songName: "In the End",
    artist: "Linkin Park",
    dateStreamed: "2024-05-14",
    streamCount: 10,
    userID: "003",
  },
  {
    songName: "Old Town Road",
    artist: "Lil Nas X",
    dateStreamed: "2024-05-15",
    streamCount: 12,
    userID: "014",
  },
  {
    songName: "Boulevard of Broken Dreams",
    artist: "Green Day",
    dateStreamed: "2024-05-16",
    streamCount: 14,
    userID: "005",
  },
  {
    songName: "Blow",
    artist: "Ed Sheeran",
    dateStreamed: "2024-05-17",
    streamCount: 9,
    userID: "006",
  },
  {
    songName: "Grenade",
    artist: "Bruno Mars",
    dateStreamed: "2024-05-18",
    streamCount: 10,
    userID: "007",
  },
  {
    songName: "Say So",
    artist: "Doja Cat",
    dateStreamed: "2024-09-19",
    streamCount: 11,
    userID: "101",
  },
  {
    songName: "Toxic",
    artist: "Britney Spears",
    dateStreamed: "2024-09-20",
    streamCount: 8,
    userID: "002",
  },
  {
    songName: "Chandelier",
    artist: "Sia",
    dateStreamed: "2024-09-21",
    streamCount: 9,
    userID: "003",
  },
  {
    songName: "Thunder",
    artist: "Imagine Dragons",
    dateStreamed: "2024-09-22",
    streamCount: 10,
    userID: "004",
  },
  {
    songName: "Counting Stars",
    artist: "OneRepublic",
    dateStreamed: "2024-09-23",
    streamCount: 12,
    userID: "005",
  },
  {
    songName: "Pumped Up Kicks",
    artist: "Foster the People",
    dateStreamed: "2024-09-24",
    streamCount: 14,
    userID: "006",
  },
  {
    songName: "Someone Like You",
    artist: "Adele",
    dateStreamed: "2024-09-25",
    streamCount: 11,
    userID: "007",
  },
  {
    songName: "Wake Me Up",
    artist: "Avicii",
    dateStreamed: "2024-09-26",
    streamCount: 8,
    userID: "001",
  },
  {
    songName: "Sicko Mode",
    artist: "Travis Scott",
    dateStreamed: "2024-09-27",
    streamCount: 12,
    userID: "032",
  },
  {
    songName: "Summertime Sadness",
    artist: "Lana Del Rey",
    dateStreamed: "2024-08-28",
    streamCount: 13,
    userID: "003",
  },
  {
    songName: "Lose Control",
    artist: "Meduza",
    dateStreamed: "2024-08-29",
    streamCount: 11,
    userID: "004",
  },
  {
    songName: "Don't Let Me Down",
    artist: "The Chainsmokers",
    dateStreamed: "2024-08-30",
    streamCount: 9,
    userID: "035",
  },
  {
    songName: "Uptown Funk",
    artist: "Mark Ronson",
    dateStreamed: "2024-08-01",
    streamCount: 15,
    userID: "006",
  },
  {
    songName: "Royals",
    artist: "Lorde",
    dateStreamed: "2024-06-02",
    streamCount: 10,
    userID: "007",
  },
  {
    songName: "Hello",
    artist: "Adele",
    dateStreamed: "2024-06-03",
    streamCount: 23,
    userID: "001",
  },
  {
    songName: "Perfect",
    artist: "Ed Sheeran",
    dateStreamed: "2024-06-04",
    streamCount: 12,
    userID: "402",
  },
  {
    songName: "Bad Romance",
    artist: "Lady Gaga",
    dateStreamed: "2024-06-05",
    streamCount: 11,
    userID: "063",
  },

  {
    songName: "Blinding Lights",
    artist: "The Weeknd",
    dateStreamed: "2024-09-01",
    streamCount: 15,
    userID: "061",
  },
  {
    songName: "Shape of You",
    artist: "Ed Sheeran",
    dateStreamed: "2024-09-02",
    streamCount: 10,
    userID: "062",
  },
  {
    songName: "Levitating",
    artist: "Dua Lipa",
    dateStreamed: "2024-09-03",
    streamCount: 8,
    userID: "063",
  },
  {
    songName: "Rolling in the Deep",
    artist: "Adele",
    dateStreamed: "2024-09-01",
    streamCount: 52,
    userID: "001",
  },
  {
    songName: "Watermelon Sugar",
    artist: "Harry Styles",
    dateStreamed: "2024-09-03",
    streamCount: 12,
    userID: "002",
  },
  {
    songName: "Peaches",
    artist: "Justin Bieber",
    dateStreamed: "2024-09-04",
    streamCount: 9,
    userID: "014",
  },
  {
    songName: "Good 4 U",
    artist: "Olivia Rodrigo",
    dateStreamed: "2024-09-05",
    streamCount: 11,
    userID: "005",
  },
  {
    songName: "Montero",
    artist: "Lil Nas X",
    dateStreamed: "2024-09-06",
    streamCount: 13,
    userID: "206",
  },
  {
    songName: "Save Your Tears",
    artist: "The Weeknd",
    dateStreamed: "2024-09-02",
    streamCount: 7,
    userID: "007",
  },
  {
    songName: "Drivers License",
    artist: "Olivia Rodrigo",
    dateStreamed: "2024-09-07",
    streamCount: 14,
    userID: "001",
  },
  {
    songName: "Stay",
    artist: "The Kid LAROI",
    dateStreamed: "2024-09-08",
    streamCount: 8,
    userID: "002",
  },
  {
    songName: "Dynamite",
    artist: "BTS",
    dateStreamed: "2024-09-09",
    streamCount: 10,
    userID: "003",
  },
  {
    songName: "Industry Baby",
    artist: "Lil Nas X",
    dateStreamed: "2024-09-10",
    streamCount: 9,
    userID: "004",
  },
  {
    songName: "Mood",
    artist: "24kGoldn",
    dateStreamed: "2024-09-11",
    streamCount: 11,
    userID: "205",
  },
  {
    songName: "positions",
    artist: "Ariana Grande",
    dateStreamed: "2024-09-12",
    streamCount: 6,
    userID: "206",
  },
  {
    songName: "Go Crazy",
    artist: "Chris Brown",
    dateStreamed: "2024-09-13",
    streamCount: 8,
    userID: "007",
  },
  {
    songName: "Kiss Me More",
    artist: "Doja Cat",
    dateStreamed: "2024-09-14",
    streamCount: 12,
    userID: "031",
  },
  {
    songName: "Butter",
    artist: "BTS",
    dateStreamed: "2024-09-15",
    streamCount: 10,
    userID: "002",
  },
  {
    songName: "Rockstar",
    artist: "DaBaby",
    dateStreamed: "2024-09-16",
    streamCount: 9,
    userID: "003",
  },
  {
    songName: "Life Goes On",
    artist: "BTS",
    dateStreamed: "2024-09-17",
    streamCount: 8,
    userID: "004",
  },
  {
    songName: "WAP",
    artist: "Cardi B",
    dateStreamed: "2024-09-18",
    streamCount: 13,
    userID: "005",
  },
  {
    songName: "Laugh Now Cry Later",
    artist: "Drake",
    dateStreamed: "2024-09-19",
    streamCount: 12,
    userID: "006",
  },
  {
    songName: "Whats Poppin",
    artist: "Jack Harlow",
    dateStreamed: "2024-09-20",
    streamCount: 11,
    userID: "007",
  },
  {
    songName: "Savage Love",
    artist: "Jawsh 685",
    dateStreamed: "2024-09-21",
    streamCount: 9,
    userID: "001",
  },
  {
    songName: "For The Night",
    artist: "Pop Smoke",
    dateStreamed: "2024-09-22",
    streamCount: 7,
    userID: "002",
  },
  {
    songName: "Roses",
    artist: "SAINt JHN",
    dateStreamed: "2024-09-23",
    streamCount: 10,
    userID: "003",
  },
  {
    songName: "Stunnin'",
    artist: "Curtis Waters",
    dateStreamed: "2024-09-24",
    streamCount: 11,
    userID: "004",
  },
  {
    songName: "Take You Dancing",
    artist: "Jason Derulo",
    dateStreamed: "2024-09-25",
    streamCount: 8,
    userID: "005",
  },
  {
    songName: "Holy",
    artist: "Justin Bieber",
    dateStreamed: "2024-08-26",
    streamCount: 6,
    userID: "006",
  },
  {
    songName: "Lonely",
    artist: "Justin Bieber",
    dateStreamed: "2024-08-27",
    streamCount: 9,
    userID: "007",
  },
  {
    songName: "Put Your Records On",
    artist: "Ritt Momney",
    dateStreamed: "2024-08-28",
    streamCount: 7,
    userID: "001",
  },
  {
    songName: "Heat Waves",
    artist: "Glass Animals",
    dateStreamed: "2024-08-29",
    streamCount: 14,
    userID: "002",
  },
  {
    songName: "Blame It On Me",
    artist: "George Ezra",
    dateStreamed: "2024-08-30",
    streamCount: 8,
    userID: "053",
  },
  {
    songName: "Dance Monkey",
    artist: "Tones and I",
    dateStreamed: "2024-08-20",
    streamCount: 20,
    userID: "058",
  },
  {
    songName: "Watermelon Sugar",
    artist: "Harry Styles",
    dateStreamed: "2024-08-15",
    streamCount: 15,
    userID: "059",
  },
  {
    songName: "Levitating",
    artist: "Dua Lipa",
    dateStreamed: "2024-04-01",
    streamCount: 7,
    userID: "010",
  },
  {
    songName: "Blinding Lights",
    artist: "The Weeknd",
    dateStreamed: "2024-06-05",
    streamCount: 25,
    userID: "011",
  },
  {
    songName: "Peaches",
    artist: "Justin Bieber",
    dateStreamed: "2024-06-06",
    streamCount: 14,
    userID: "012",
  },
  {
    songName: "Good 4 U",
    artist: "Olivia Rodrigo",
    dateStreamed: "2024-06-08",
    streamCount: 16,
    userID: "013",
  },
  {
    songName: "Save Your Tears",
    artist: "The Weeknd",
    dateStreamed: "2024-08-09",
    streamCount: 18,
    userID: "014",
  },
  {
    songName: "Industry Baby",
    artist: "Lil Nas X",
    dateStreamed: "2024-06-11",
    streamCount: 22,
    userID: "015",
  },
  {
    songName: "Stay",
    artist: "The Kid LAROI",
    dateStreamed: "2024-06-12",
    streamCount: 13,
    userID: "219",
  },
  {
    songName: "Mood",
    artist: "24kGoldn",
    dateStreamed: "2024-09-13",
    streamCount: 23,
    userID: "279",
  },
];
